server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/items_db?createDatabaseIfNotExist=true
    username: root
    password: 'root123!'
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        highlight_sql: true
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest